/* Main.c file generated by New Project wizard
 *
 * Created:   qua dez 9 2020
 * Processor: LPC1114FN28/102
 * Compiler:  GCC for ARM
 */

#include <LPC11xx.h>

#define DEBUG_FLAG 1

#include "lib/adc.h"
#include "lib/gpio.h"
#include "lib/pwm.h"
#include "lib/timer.h"

#if DEBUG_FLAG
#include "lib/uart.h"
#endif


int main(void) {      //Toggle a GPIO (FBD48 pin 23, PIO0_7, controls the LED on the LPC Expresso PCB)

     init_GPIO();                     
     init_UART();
     set_DIR(3,INPUT);
     //unsigned int i = 0;
 
     while(1){                      //infinite loop
          if(read_digital_gpio(3)==HIGH){
               printf_int(123456789);
               printf_string("ab|gv");
               printf_float(12.5359);                                            
          }
          
     }
      return 0 ;
}
